name: The Bot Host
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git pull origin ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Clone repository
        run: git clone https://github.com/GataNina-Li/GataBot-MD
      
      - name: Install dependencies
        run: cd GataBot-MD && rm -rf pakcage-lock.json && npm i

      - name: TErM
        run: export TERM=xterm
      
      - name: Start The Code
        run: node index.js &
          
      - name: delete the cache and Commit the logs
        run: |
          cd GataBot-MD
          rm -rf tmp
          mkdir tmp
          rm -rf node_modules
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "out session update" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      
      - name: Stop workflow
        run: exit 0
